### PR TITLE
HotePasteHelper plugin

### PR DESCRIPTION
**Pull request by rolandtoth**

### CODE REVIEW

**Comment by aviaryan** [comment]
Hey @rolandtoth 
I see you have created a lot of hotstrings and some are named like 'date', 'time' etc... 
Now these are common day-to-day used words and there is a chance people using your plugin may need to type the word "date" and instead end up pasting the current_date. 
So I suggest you add a suffix to your hotstring names (like `hph`)... 
- `hphdate`, `hphtime`, .. etc

What do you think?

**Comment by rolandtoth** [comment]
I agree, and I usually add at least a trailing "x" to them: datex, timex, etc. I removed them for easier understanding for beginners (these are just examples).
However, these hotstrings are expanded with TAB so it is not so easy to fire an abbreviation accidentally.
Now I added "x" suffix for those hotstrings that were too common. In my experience it is easier to use suffixes instead of prefixes.

**Comment by aviaryan** [comment]
I see you have created a lot of global variables in hotpastehelper.ahk . 
Are you sure they work ? bcoz as the `global` are in the hotpastehelper.ahk, they are not run by Clipjump auto-execute section. I include all plugins at the last in clipjump.ahk so there is no chance the global declarations are executed.
Please recheck this.
You can also use [STORE](http://clipjump.sourceforge.net/docs/custom.html#store) variable if you want.

**Comment by rolandtoth** [comment]
Hi,

yes, they are working - I use HPH with ClipJump for months now. 

The documentations says
"1.Variable Names in plugin files that are included (not external) should start with z. This is because Clipjump doesn't uses any variable starting with 'z' and so this is the best option to avoid variable conflicts. "

That's why I used globals. There are some not starting with "z" - I will fix them later.

Or do you think I should use STORE instead?

**Comment by aviaryan** [comment]
Good that it works. My main concern is not with the variable names but the `global` declaration. I think they are not activated. But maybe I am wrong bcuz you have been using it.
I would like that you fix those variables without `z`.
I will merge it then.

**Comment by rolandtoth** [comment]
Hi,

added "z" to the globals.

I will fill the wiki though I have many things to do nowadays so it will require some time.

**Pull request merged**
